Repository sparta-Sounganization/Botanify, pull requests merged in 2024-12, with the labels that each got.

#4 프로젝트 생성
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sounganization/botanify/BotanifyApplication.java
  src/main/java/com/sounganization/botanify/common/entity/Timestamped.java
  src/main/java/com/sounganization/botanify/common/exception/CustomException.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionGroupResponse.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionResponse.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sounganization/botanify/domain/community/controller/CommentController.java
  src/main/java/com/sounganization/botanify/domain/community/controller/PostController.java
  src/main/java/com/sounganization/botanify/domain/community/dto/.gitkeep
  src/main/java/com/sounganization/botanify/domain/community/entity/Comment.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Post.java
  src/main/java/com/sounganization/botanify/domain/community/enums/.gitkeep
  src/main/java/com/sounganization/botanify/domain/community/mapper/.gitkeep
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentRepository.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PostRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/CommentService.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/java/com/sounganization/botanify/domain/terrarium/controller/DiaryController.java
  src/main/java/com/sounganization/botanify/domain/terrarium/controller/PlantController.java
  src/main/java/com/sounganization/botanify/domain/terrarium/dto/PlantPostRequest.java
  src/main/java/com/sounganization/botanify/domain/terrarium/entity/Diary.java
  src/main/java/com/sounganization/botanify/domain/terrarium/entity/Plant.java
  src/main/java/com/sounganization/botanify/domain/terrarium/enums/.gitkeep
  src/main/java/com/sounganization/botanify/domain/terrarium/mapper/.gitkeep
  src/main/java/com/sounganization/botanify/domain/terrarium/repository/DiaryRepository.java
  src/main/java/com/sounganization/botanify/domain/terrarium/repository/PlantRepository.java
  src/main/java/com/sounganization/botanify/domain/terrarium/service/DiaryService.java
  src/main/java/com/sounganization/botanify/domain/terrarium/service/PlantService.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/sounganization/botanify/BotanifyApplicationTests.java
Labels: enhancement

#13 공통부분 발견된 사소한 문제점 수정
  src/main/java/com/sounganization/botanify/common/dto/res/ExceptionGroupResDto.java
  src/main/java/com/sounganization/botanify/common/dto/res/ExceptionResDto.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionResponse.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sounganization/botanify/domain/community/controller/CommentController.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/PlantReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/entity/User.java
Labels: bug

#16 Timestamped 상속체들의 softDelete 메서드 임시 구현
  src/main/java/com/sounganization/botanify/common/entity/Timestamped.java
Labels: bug

#14 Docker에 MYSQL 8.0 추가 및 Github Actions(CI 기능 추가)
  .github/workflows/runtest.yml
  docker-compose.yml
  src/main/resources/application.yml
Labels: enhancement

#26 Spring Security 오류 해결
  build.gradle
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/sounganization/botanify/common/security/UserDetailsImpl.java
  src/main/java/com/sounganization/botanify/common/util/JwtUtil.java
  src/main/java/com/sounganization/botanify/domain/user/mapper/UserMapper.java
Labels: bug

#21 댓글(Comment) CRUD
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/util/JwtUtil.java
  src/main/java/com/sounganization/botanify/domain/community/controller/CommentController.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/CommentReqDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/CommentResDto.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Comment.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/.gitkeep
  src/main/java/com/sounganization/botanify/domain/community/mapper/CommentMapper.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/CommentService.java
Labels: enhancement

#27 일지(DIARY) 기능 개선, 컨벤션 통일
  src/main/java/com/sounganization/botanify/domain/garden/controller/DiaryController.java
  src/main/java/com/sounganization/botanify/domain/garden/mapper/DiaryMapper.java
  src/main/java/com/sounganization/botanify/domain/garden/service/DiaryService.java
Labels: enhancement

#22 식물(PLANT) CRUD
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/domain/garden/controller/PlantController.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/PlantReqDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/PlantResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/entity/Plant.java
  src/main/java/com/sounganization/botanify/domain/garden/entity/Species.java
  src/main/java/com/sounganization/botanify/domain/garden/mapper/PlantMapper.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/DiaryRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/service/PlantService.java
Labels: enhancement

#32 게시글(Post) - 병합 후 변경 사항
  src/main/java/com/sounganization/botanify/domain/community/controller/PostController.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/CommentTempDto.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
Labels: enhancement

#34 댓글(Comment) CRUD V1 - 병합 후 변경 사항
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Comment.java
  src/main/java/com/sounganization/botanify/domain/community/service/CommentService.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
Labels: enhancement

#37 품종(Species) CRUD 간단 구현
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/sounganization/botanify/domain/garden/controller/SpeciesController.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/SpeciesReqDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/SpeciesResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/entity/Species.java
  src/main/java/com/sounganization/botanify/domain/garden/mapper/SpeciesMapper.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/service/SpeciesService.java
Labels: enhancement

#40 USER CRUD + 리뷰 피드백 반영
  docker-compose.yml
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/security/UserDetailsImpl.java
  src/main/java/com/sounganization/botanify/common/util/JwtUtil.java
  src/main/java/com/sounganization/botanify/domain/auth/controller/AuthController.java
  src/main/java/com/sounganization/botanify/domain/auth/controller/ExampleController.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/AuthReqDto.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/SigninReqDto.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/SignupReqDto.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/res/AuthResDto.java
  src/main/java/com/sounganization/botanify/domain/auth/service/AuthService.java
  src/main/java/com/sounganization/botanify/domain/user/controller/UserController.java
  src/main/java/com/sounganization/botanify/domain/user/dto/req/UserDeleteReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/req/UserReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/req/UserUpdateReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/res/UserPlantsResDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/res/UserPostsResDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/res/UserResDto.java
  src/main/java/com/sounganization/botanify/domain/user/entity/User.java
  src/main/java/com/sounganization/botanify/domain/user/mapper/UserMapper.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserRepository.java
  src/main/java/com/sounganization/botanify/domain/user/service/UserDetailsServiceImpl.java
  src/main/java/com/sounganization/botanify/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#39 게시글(Post) - 단건조회 queryDsl
  build.gradle
  src/main/java/com/sounganization/botanify/common/config/QueryDslConfig.java
  src/main/java/com/sounganization/botanify/common/dto/res/CommonResDto.java
  src/main/java/com/sounganization/botanify/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sounganization/botanify/domain/auth/controller/AuthController.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/res/AuthResDto.java
  src/main/java/com/sounganization/botanify/domain/auth/service/AuthService.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/CommentTempDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/PostWithCommentResDto.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Comment.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/PostMapper.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/java/com/sounganization/botanify/domain/user/controller/UserController.java
  src/main/java/com/sounganization/botanify/domain/user/projection/UserProjection.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserRepository.java
  src/main/java/com/sounganization/botanify/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#44 관리자 사용자 프로필 조회 기능 구현 + review 해결 + Docker에 Redis 띄우기
  docker-compose.yml
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/domain/admin/controller/AdminController.java
  src/main/java/com/sounganization/botanify/domain/admin/service/AdminService.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/SignupReqDto.java
  src/main/java/com/sounganization/botanify/domain/auth/service/AuthService.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/CommentReqDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/PostReqDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/PostUpdateReqDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/PostListResDto.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PostRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/PlantResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/PlantRepository.java
  src/main/java/com/sounganization/botanify/domain/user/controller/UserController.java
  src/main/java/com/sounganization/botanify/domain/user/dto/req/UserUpdateReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/res/UserPlantsResDto.java
  src/main/java/com/sounganization/botanify/domain/user/service/UserDetailsServiceImpl.java
  src/main/java/com/sounganization/botanify/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: bug, enhancement

#45 인기글(Popular posts) 캐싱 처리
  docker-compose.yml
  src/main/java/com/sounganization/botanify/common/config/redis/RedisConfig.java
  src/main/java/com/sounganization/botanify/domain/community/controller/PopularPostController.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/PopularPostResDto.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Comment.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/PostMapper.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PopularPostRedisRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/CommentService.java
  src/main/java/com/sounganization/botanify/domain/community/service/PopularPostService.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/resources/application.yml
Labels: enhancement

#46 인기글 캐싱 - 주기적 점수 update의 scheduling
  src/main/java/com/sounganization/botanify/BotanifyApplication.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PostRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PopularPostService.java
Labels: enhancement

#47 게시글(Post) 조회수 중복 방지
  src/main/java/com/sounganization/botanify/BotanifyApplication.java
  src/main/java/com/sounganization/botanify/domain/community/controller/PostController.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/ViewHistoryDto.java
  src/main/java/com/sounganization/botanify/domain/community/entity/ViewHistory.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/ViewHistoryMapper.java
  src/main/java/com/sounganization/botanify/domain/community/repository/ViewHistoryCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/community/repository/ViewHistoryCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/community/repository/ViewHistoryRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/java/com/sounganization/botanify/domain/community/service/SchedulerService.java
  src/main/java/com/sounganization/botanify/domain/community/service/ViewHistoryRedisService.java
Labels: enhancement

#51 POST 도메인 기준 테스트 코드 작성
  src/main/resources/application-test.yml
  src/test/java/com/sounganization/botanify/domain/community/controller/PostControllerTest.java
  src/test/java/com/sounganization/botanify/domain/community/entity/PostTest.java
  src/test/java/com/sounganization/botanify/domain/community/repository/PostRepositoryTest.java
  src/test/java/com/sounganization/botanify/domain/community/service/PostServiceTest.java
  src/test/resources/application-test.yml
Labels: testcode

#52 조회기록 테스트 코드
  src/test/java/com/sounganization/botanify/ViewHistory/ViewHistorySchedulerTest.java
Labels: testcode

#56 1:1 private 실시간 채팅 기능 구현
  build.gradle
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/config/websocket/ChatWebSocketHandler.java
  src/main/java/com/sounganization/botanify/common/config/websocket/WebSocketConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/sounganization/botanify/domain/chat/controller/ChatController.java
  src/main/java/com/sounganization/botanify/domain/chat/dto/req/ChatMessageReqDto.java
  src/main/java/com/sounganization/botanify/domain/chat/dto/res/ChatMessageResDto.java
  src/main/java/com/sounganization/botanify/domain/chat/dto/res/ChatRoomResDto.java
  src/main/java/com/sounganization/botanify/domain/chat/dto/res/ErrorMessageDto.java
  src/main/java/com/sounganization/botanify/domain/chat/entity/ChatMessage.java
  src/main/java/com/sounganization/botanify/domain/chat/entity/ChatRoom.java
  src/main/java/com/sounganization/botanify/domain/chat/mapper/ChatMessageMapper.java
  src/main/java/com/sounganization/botanify/domain/chat/mapper/ChatRoomMapper.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/service/ChatMessageService.java
  src/main/java/com/sounganization/botanify/domain/chat/service/ChatRoomService.java
  src/main/java/com/sounganization/botanify/domain/community/service/CommentService.java
Labels: enhancement

#54 소셜 로그인 기능 구현
  aws/buckets.sh
  build.gradle
  docker-compose.yml
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/filter/GoogleJwtAuthenticationFilter.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/sounganization/botanify/common/util/GoogleJwtAuthenticationProvider.java
  src/main/java/com/sounganization/botanify/common/util/GoogleJwtValidator.java
  src/main/java/com/sounganization/botanify/common/util/JwtUtil.java
  src/main/java/com/sounganization/botanify/domain/auth/controller/ExampleController.java
  src/main/java/com/sounganization/botanify/domain/auth/service/AuthService.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: enhancement

#59 이미지 업로드 기능 구현
  .gitignore
  aws/01-create-bucket.sh
  aws/02-set-cors.sh
  aws/buckets.sh
  build.gradle
  docker-compose.yml
  src/main/java/com/sounganization/botanify/common/config/WebConfig.java
  src/main/java/com/sounganization/botanify/common/config/s3/S3Config.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/PostReqDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/req/PostUpdateReqDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/PopularPostResDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/PostListResDto.java
  src/main/java/com/sounganization/botanify/domain/community/dto/res/PostWithCommentResDto.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Post.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/PostMapper.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/ViewHistoryMapper.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PopularPostRedisRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/java/com/sounganization/botanify/domain/s3/controller/S3Controller.java
  src/main/java/com/sounganization/botanify/domain/s3/dto/req/ImageUploadReqDto.java
  src/main/java/com/sounganization/botanify/domain/s3/dto/res/ImageUrlResDto.java
  src/main/java/com/sounganization/botanify/domain/s3/service/S3Service.java
  src/main/resources/application.yml
Labels: enhancement

#62 댓글과 대댓글 code의 개선 및 최적화
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/domain/chat/controller/ChatController.java
  src/main/java/com/sounganization/botanify/domain/community/entity/Comment.java
  src/main/java/com/sounganization/botanify/domain/community/mapper/CommentMapper.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/community/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/community/service/CommentService.java
Labels: bug

#64 GoogleJwtAuthenticationProvider -> nx, ny 추가
  src/main/java/com/sounganization/botanify/common/util/GoogleJwtAuthenticationProvider.java
Labels: bug

#69 Social 로그인 (Google) 주소 수정 기능 추가
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/filter/GoogleJwtAuthenticationFilter.java
  src/main/java/com/sounganization/botanify/common/util/GoogleJwtAuthenticationProvider.java
  src/main/java/com/sounganization/botanify/common/util/GridUtil.java
  src/main/java/com/sounganization/botanify/common/util/JwtUtil.java
  src/main/java/com/sounganization/botanify/domain/auth/service/AuthService.java
  src/main/java/com/sounganization/botanify/domain/user/controller/UserController.java
  src/main/java/com/sounganization/botanify/domain/user/dto/req/AddressReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/dto/req/UserUpdateReqDto.java
  src/main/java/com/sounganization/botanify/domain/user/entity/User.java
  src/main/java/com/sounganization/botanify/domain/user/enums/UserRole.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/user/repository/UserRepository.java
  src/main/java/com/sounganization/botanify/domain/user/service/UserService.java
  src/main/java/com/sounganization/botanify/domain/weather/service/LocationService.java
  src/test/java/com/sounganization/botanify/domain/community/controller/PostControllerTest.java
  src/test/java/com/sounganization/botanify/domain/community/service/PostServiceTest.java
Labels: bug, enhancement

#72 1:1 실시간 채팅 기능 성능 최적화
  src/main/java/com/sounganization/botanify/common/config/redis/RedisConfig.java
  src/main/java/com/sounganization/botanify/common/config/websocket/ChatMessageListener.java
  src/main/java/com/sounganization/botanify/common/config/websocket/ChatWebSocketHandler.java
  src/main/java/com/sounganization/botanify/domain/chat/components/ChatDataCleanupScheduler.java
  src/main/java/com/sounganization/botanify/domain/chat/components/ChatMessageConstants.java
  src/main/java/com/sounganization/botanify/domain/chat/entity/ChatMessage.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/chat/service/ChatMessageService.java
Labels: enhancement

#81 식물 외부 API 호출 기능 구현
  aws/02-set-cors.sh
  build.gradle
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/config/restTemplate/RestTemplateConfig.java
  src/main/java/com/sounganization/botanify/common/config/webClient/WebClientConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/sounganization/botanify/common/service/SchedulerService.java
  src/main/java/com/sounganization/botanify/domain/community/service/SchedulerService.java
  src/main/java/com/sounganization/botanify/domain/garden/controller/SpeciesController.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/SpeciesReqDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/SpeciesDetailResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/SpeciesResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/entity/Species.java
  src/main/java/com/sounganization/botanify/domain/garden/mapper/SpeciesMapper.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/garden/service/SpeciesService.java
  src/main/java/com/sounganization/botanify/domain/plantApi/controller/PlantApiAllController.java
  src/main/java/com/sounganization/botanify/domain/plantApi/controller/PlantApiEachController.java
  src/main/java/com/sounganization/botanify/domain/plantApi/dto/res/CategoryResDto.java
  src/main/java/com/sounganization/botanify/domain/plantApi/dto/res/PlantApiResDto.java
  src/main/java/com/sounganization/botanify/domain/plantApi/dto/res/PlantDetailResDto.java
  src/main/java/com/sounganization/botanify/domain/plantApi/dto/res/PlantListResDto.java
  src/main/java/com/sounganization/botanify/domain/plantApi/service/PlantApiAllService.java
  src/main/java/com/sounganization/botanify/domain/plantApi/service/PlantApiEachService.java
  src/main/java/com/sounganization/botanify/domain/plantApi/util/XmlUtils.java
  src/main/java/com/sounganization/botanify/domain/weather/service/WeatherService.java
  src/main/resources/application.yml
  src/test/java/com/sounganization/botanify/common/service/SchedulerServiceTest.java
Labels: enhancement

#83 Feat/weather#82
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/SignupReqDto.java
  src/main/java/com/sounganization/botanify/domain/weather/service/WeatherService.java
Labels: bug, enhancement

#86 전체 게시판 조회 상세 쿼리 (검색어, 정렬 등) 구현
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/domain/community/controller/PostController.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PostCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PostCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/community/repository/PostRepository.java
  src/main/java/com/sounganization/botanify/domain/community/service/PostService.java
  src/main/java/com/sounganization/botanify/domain/user/entity/User.java
  src/test/java/com/sounganization/botanify/domain/community/controller/PostControllerTest.java
  src/test/java/com/sounganization/botanify/domain/community/service/PostServiceTest.java
Labels: enhancement

#88 applicaion.yml 변경
  src/main/resources/application.yml
Labels: enhancement

#87 식물 물주기 알람 기능
  gradlew
  src/main/java/com/sounganization/botanify/common/config/onesignal/OneSignalClient.java
  src/main/java/com/sounganization/botanify/common/config/restTemplate/RestTemplateConfig.java
  src/main/java/com/sounganization/botanify/common/config/webClient/WebClientConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/service/NotificationService.java
  src/main/java/com/sounganization/botanify/domain/chat/entity/ChatMessage.java
  src/main/java/com/sounganization/botanify/domain/chat/entity/ChatRoom.java
  src/main/java/com/sounganization/botanify/domain/garden/controller/PlantAlarmController.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/PlantAlarmReqDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/PlantAlarmUpdateReqDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/PlantAlarmResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/entity/PlantAlarm.java
  src/main/java/com/sounganization/botanify/domain/garden/mapper/PlantAlarmMapper.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/PlantAlarmCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/PlantAlarmCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/PlantAlarmRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/scheduler/PlantAlarmScheduler.java
  src/main/java/com/sounganization/botanify/domain/garden/service/PlantAlarmService.java
  src/test/java/com/sounganization/botanify/domain/garden/service/NotificationServiceTest.java
  src/test/java/com/sounganization/botanify/domain/garden/service/PlantAlarmSchedulerTest.java
  src/test/java/com/sounganization/botanify/utils/PlantAlarmTestUtils.java
Labels: enhancement
