Repository sparta-Sounganization/Botanify, pull requests merged in 2025-01, with the labels that each got.

#92 회원가입의 Email 인증
  build.gradle
  src/main/java/com/sounganization/botanify/common/config/mail/MailConfig.java
  src/main/java/com/sounganization/botanify/common/config/redis/EmailVerificationProperties.java
  src/main/java/com/sounganization/botanify/common/config/redis/EmailVerificationRedisConfig.java
  src/main/java/com/sounganization/botanify/common/exception/ExceptionStatus.java
  src/main/java/com/sounganization/botanify/common/service/EmailService.java
  src/main/java/com/sounganization/botanify/domain/auth/controller/AuthController.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/EmailVerificationCodeReqDto.java
  src/main/java/com/sounganization/botanify/domain/auth/dto/req/EmailVerificationReqDto.java
  src/main/java/com/sounganization/botanify/domain/auth/service/AuthService.java
  src/main/java/com/sounganization/botanify/domain/auth/service/EmailVerificationService.java
Labels: enhancement

#93 품종 캐싱
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/sounganization/botanify/common/service/SchedulerService.java
  src/main/java/com/sounganization/botanify/domain/garden/controller/SpeciesControllerV2.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/SpeciesDetailResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/res/SpeciesResDto.java
  src/main/java/com/sounganization/botanify/domain/garden/mapper/SpeciesMapper.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesCacheRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/garden/repository/SpeciesCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/garden/service/SpeciesService.java
Labels: enhancement

#96 plantControllerTest 구현
  src/main/java/com/sounganization/botanify/common/config/SecurityConfig.java
  src/main/java/com/sounganization/botanify/common/config/redis/RedisConfig.java
  src/main/java/com/sounganization/botanify/common/config/s3/S3Config.java
  src/main/java/com/sounganization/botanify/common/util/JwtUtil.java
  src/test/java/com/sounganization/botanify/domain/garden/controller/PlantControllerTest.java
  src/test/java/com/sounganization/botanify/domain/garden/controller/TestS3Config.java
  src/test/java/com/sounganization/botanify/domain/garden/controller/TestSecurityConfig.java
  src/test/resources/application-test.yml
Labels: testcode

#97 채팅 기능 Bug 수정
  src/main/java/com/sounganization/botanify/common/config/websocket/service/WebSocketChatService.java
  src/main/java/com/sounganization/botanify/domain/chat/components/ChatFailureHandler.java
  src/main/java/com/sounganization/botanify/domain/chat/event/ChatMessageEvent.java
  src/main/java/com/sounganization/botanify/domain/chat/service/ChatMessageService.java
Labels: bug

#101 스케줄러서비스 테스트코드 버그 수정
  src/test/java/com/sounganization/botanify/common/service/SchedulerServiceTest.java
Labels: bug, testcode

#103 이미지 업로드 로직 S3 실주소와 호환되도록 개선
  src/main/java/com/sounganization/botanify/common/config/s3/S3Config.java
  src/main/java/com/sounganization/botanify/domain/s3/service/S3Service.java
Labels: enhancement

#105 Post 도메인 단위테스트(Controller, Service) 주석 해제 후 갱신
  src/test/java/com/sounganization/botanify/domain/community/controller/PostControllerTest.java
  src/test/java/com/sounganization/botanify/domain/community/service/PostServiceTest.java
Labels: bug, testcode

#106 comment 서비스 테스트
  src/test/java/com/sounganization/botanify/domain/community/service/CommentServiceTest.java
Labels: testcode

#108 Plant 테스트코드 주석처리
  src/test/java/com/sounganization/botanify/domain/garden/controller/PlantControllerTest.java
Labels: bug, testcode

#109 식물 알람 DTO에 validation 추가
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/PlantAlarmReqDto.java
  src/main/java/com/sounganization/botanify/domain/garden/dto/req/PlantAlarmUpdateReqDto.java
Labels: bug

#111 메일 주소 no_reply@botanify.site 로 변경 / ssl = true 로 변경
  src/main/java/com/sounganization/botanify/common/config/mail/MailConfig.java
Labels: bug

#113 하이웍스에 맞게 MailConfig 수정
  prometheus/config/prometheus.yml
  src/main/java/com/sounganization/botanify/common/config/mail/MailConfig.java
Labels: bug

#115 도메인 인증 실패로 롤백
  src/main/java/com/sounganization/botanify/common/config/mail/MailConfig.java
Labels: bug

#120 Chat 기능 bug fix
  .DS_Store
  Botanify_ERD.png
  README.md
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/sounganization/botanify/common/config/TransactionConfig.java
  src/main/java/com/sounganization/botanify/common/config/async/AsyncConfig.java
  src/main/java/com/sounganization/botanify/common/config/redis/RedisConfig.java
  src/main/java/com/sounganization/botanify/common/config/websocket/ChatMessageListener.java
  src/main/java/com/sounganization/botanify/common/config/websocket/WebSocketConfig.java
  src/main/java/com/sounganization/botanify/common/config/websocket/handler/ChatWebSocketHandler.java
  src/main/java/com/sounganization/botanify/common/config/websocket/handler/ConnectionFailureHandler.java
  src/main/java/com/sounganization/botanify/common/config/websocket/service/MessageBroadcastService.java
  src/main/java/com/sounganization/botanify/common/config/websocket/service/WebSocketChatService.java
  src/main/java/com/sounganization/botanify/domain/chat/components/ChatFailureHandler.java
  src/main/java/com/sounganization/botanify/domain/chat/dto/req/ChatMessageReqDto.java
  src/main/java/com/sounganization/botanify/domain/chat/entity/ChatMessage.java
  src/main/java/com/sounganization/botanify/domain/chat/event/ChatMessageEvent.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatMessageCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomCustomRepository.java
  src/main/java/com/sounganization/botanify/domain/chat/repository/ChatRoomCustomRepositoryImpl.java
  src/main/java/com/sounganization/botanify/domain/chat/service/ChatMessageService.java
  src/main/resources/.DS_Store
  src/main/resources/static/.DS_Store
  src/main/resources/static/images/ERD_최종.jpeg
  src/test/java/com/sounganization/botanify/domain/chat/ChatFailureHandlerTest.java
  src/test/java/com/sounganization/botanify/domain/chat/ConnectionFailureHandlerTest.java
Labels: bug
